[build]
  base = "/"  # Base directory is the root of the repository
  publish = "out"  # The directory where your built files go (adjust as necessary)
  command = "npm run build"  # Your build command (or Playwright command, etc.)

  # For Netlify-specific configuration:
  netlify_base = "netlify"  # Base directory for Netlify build
  netlify_publish = "netlify/out"  # The output directory for Netlify build

