[build]
  base = "/"  # Base directory is the root of the repository
  publish = "out"  # The directory where your built files go (adjust as necessary)
  command = "npm run build"  # Your build command (or Playwright command, etc.)

[build]
  base = "netlify"
  publish = "netlify/out"
  command = "npm run build"
